# Generated by Django 5.2.4 on 2025-08-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejalashtirilgan vaqt')),
                ('recurrence', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16, null=True, verbose_name='Davriylik')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
