# Generated by Django 5.2.4 on 2025-08-05 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(default=0, verbose_name='Foydalanuvchi idsi')),
                ('user_name', models.CharField(max_length=50, verbose_name='Xabar qabul qiluvchi Ismi')),
                ('phone_number', models.IntegerField(default=0, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name="qo'shilgan vaqt")),
                ('is_active', models.BooleanField(default=False, verbose_name='Yuborilgan/Yuborilmagan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
