# Generated by Django 5.2.4 on 2025-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='send_time',
            field=models.DateTimeField(verbose_name='Yuborish vaqti'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user_id',
            field=models.IntegerField(verbose_name='Foydalanuvchi idsi'),
        ),
    ]
