# Generated by Django 5.2.4 on 2025-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_messagemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='status',
            field=models.CharField(choices=[('waiting', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi')], default='waiting', max_length=10, verbose_name='Xabar holati'),
        ),
    ]
