# Generated by Django 5.2.4 on 2025-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_messagemodel_is_active_messagemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='daily_repeat',
            field=models.BooleanField(default=False, verbose_name='Har kuni yuborilsinmi'),
        ),
    ]
