# Generated by Django 5.2.4 on 2025-08-07 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_messagemodel_daily_repeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePharmacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(verbose_name='Foydalanuvchi idsi')),
                ('user_name', models.CharField(max_length=50, verbose_name='Xabar qabul qiluvchi Ismi')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('send_time', models.DateTimeField(verbose_name='Yuborish vaqti')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi')], default='waiting', max_length=10, verbose_name='Xabar holati')),
                ('daily_repeat', models.BooleanField(default=False, verbose_name='Har kuni yuborilsinmi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
