# Generated by Django 5.2.4 on 2025-08-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_messagepharmacymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagePharmacyModel',
        ),
    ]
