# Generated by Django 5.2.5 on 2025-08-13 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_delete_messagepharmacymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
