# Generated by Django 5.2.5 on 2025-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_messagemodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='User idsi'),
        ),
    ]
