# Generated by Django 5.2.4 on 2025-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('dosage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dozasi')),
                ('composition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tarkibi')),
                ('type', models.CharField(choices=[('pachka', 'Пачка'), ('dona', 'Дона')], default='dona', max_length=50, verbose_name='Dori turi')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Necha dona')),
                ('pills_per_package', models.IntegerField(default=1, verbose_name='Har bir pachkada necha dona')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniya nomi')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kirib kelish narxi')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sotish narxi')),
                ('total_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Umumiy kirib kelish summa')),
                ('total_selling_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Umumiy sotish summa')),
                ('total_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Umumiy necha dona ekanligi')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
