# Generated by Django 5.2.4 on 2025-08-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='total_stock',
            field=models.IntegerField(default=0, verbose_name='Umumiy necha dona ekanligi'),
        ),
    ]
