# Generated by Django 5.2.4 on 2025-08-06 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_archived_productmodel_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='initial_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Boshlang'ich qarz"),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='remaining_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Qolgan qarz'),
        ),
        migrations.CreateModel(
            name='DebtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Boshlang'ich qarz")),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qolgan qarz')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
            },
        ),
    ]
