# Generated by Django 5.2.4 on 2025-08-11 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_initial_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='loose_pills',
            field=models.IntegerField(default=0, verbose_name='Qoldiq dona'),
        ),
    ]
