# Generated by Django 5.2.4 on 2025-08-02 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProductReceiptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy narx')),
                ('total_count', models.IntegerField(default=0, verbose_name='Umumiy soni')),
                ('products', models.JSONField(default=list, verbose_name="Mahsulotlar ro'yxati")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vlaedec')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_receipts', to='pharmacy.pharmacymodel')),
            ],
            options={
                'verbose_name': 'Pharmacy Product Receipt',
                'verbose_name_plural': 'Pharmacy Product Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
