# Generated by Django 5.2.4 on 2025-08-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacyproductreceiptmodel'),
        ('products', '0004_productmodel_initial_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacymedicinetransaction',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_transactions', to='products.productmodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.productmodel'),
        ),
        migrations.DeleteModel(
            name='MedicineModel',
        ),
    ]
