# Generated by Django 5.2.4 on 2025-08-07 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacymedicinetransaction_medicine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарства')),
                ('dosage', models.CharField(max_length=50, verbose_name='Дозировка')),
                ('pills_per_package', models.IntegerField(verbose_name='Количество таблеток в упаковке')),
                ('price_per_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за упаковку')),
                ('price_per_pill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за таблетку')),
                ('price_type', models.CharField(choices=[('package', 'За упаковку'), ('pill', 'За таблетку')], default='package', max_length=10, verbose_name='Тип цены')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Проданное количество')),
                ('given_quantity', models.IntegerField(default=0, verbose_name='Выданное количество')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pharmacymedicinetransaction',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_transactions', to='pharmacy.medicinemodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pharmacy.medicinemodel'),
        ),
    ]
