# Generated by Django 5.2.4 on 2025-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_debtpayment_pharmacydebt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacydebt',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pharmacydebt',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='pharmacymodel',
            name='remaining_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Остаток долга'),
        ),
        migrations.AddField(
            model_name='pharmacymodel',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общий долг'),
        ),
        migrations.DeleteModel(
            name='DebtPayment',
        ),
        migrations.DeleteModel(
            name='PharmacyDebt',
        ),
    ]
