# Generated by Django 5.2.4 on 2025-08-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_remove_pharmacydebt_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalmodel',
            name='phone',
        ),
    ]
