# Generated by Django 5.2.4 on 2025-08-10 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_hospitalmodel_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDebtPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='pharmacy.pharmacymodel')),
            ],
            options={
                'verbose_name': 'Pharmacy Debt Payment',
                'verbose_name_plural': 'Pharmacy Debt Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
