# Generated by Django 5.2.5 on 2025-08-13 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacydebtpaymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacymodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
