# Generated by Django 5.2.5 on 2025-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_pharmacymodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дозировка'),
        ),
    ]
