# Generated by Django 5.2.5 on 2025-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
