# Generated by Django 5.2.4 on 2025-08-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0002_pharmacyproductreceiptmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.JSONField(blank=True, default=list)),
                ('polyclinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='pharmacy.hospitalmodel')),
            ],
        ),
    ]
