# Generated by Django 5.2.4 on 2025-08-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacyproductreceiptmodel'),
        ('polyclinic_doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Apteka', to='pharmacy.pharmacymodel'),
            preserve_default=False,
        ),
    ]
