# Generated by Django 5.2.4 on 2025-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_doctors', '0002_doctormodel_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='pharmacy',
            field=models.JSONField(blank=True, default=list, verbose_name="Aptekalar ro'yxati"),
        ),
    ]
