# Generated by Django 5.2.4 on 2025-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_doctors', '0003_alter_doctormodel_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
