# Generated by Django 5.2.5 on 2025-08-14 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_doctors', '0004_doctormodel_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
